# 网站基本设置
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# 网站标题，会显示在浏览器标签页上
title: Home Page for Yuxuan Liu
# 你的联系邮箱
email: "liuyx2005@sjtu.edu.com"
# 网站的一句话描述，会用于搜索引擎优化
description: Undergraduate of John Hopcroft Class 2024, Shanghai Jiao Tong University
# 错误修正 1: 下面这行多余的模板注释已被删除。

# 网站域名设置 (非常重要!)
baseurl: ""
url: "https://osc-7.github.io"

# 社交媒体和学术档案链接
# 在下面填入你的用户名或ID即可自动生成链接，不需要的可以留空或在行首加 # 注释掉
# twitter_username:
github_username: "osc-7"
# linkedin_username:
# scholar:
#   id:
#   last_name: Liu
# orcid:
# research_gate_profile:

# 个人信息 (会显示在主页左侧)
author:
  # 错误修正 2: 下面所有缩进都已换成正确的半角空格，这是最关键的修改！
  name: "刘宇轩 (Yuxuan Liu)"
  avatar: "/images/IMG_7125.jpeg
  bio: "Hi! I'm Yuxuan Liu, undergraduate of John Hopcroft Class 2024, SJTU. I'm currently exploring my research interest, and I'm looking forward to start a research internship!"
  location: "Shanghai, China"
  employer: "Shanghai Jiao Tong University"

# 其他设置 (一般无需修改)
# Build settings
markdown: kramdown
permalink: /:categories/:title/
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Exclude from processing
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap

# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-xxxxxxxxxx"
    anonymize_ip: false
